# Generated by Django 5.0.6 on 2024-06-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='located',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='located_enterprise', to='users.enterprise'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_device', to='sensors.device', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='located',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_located', to='sensors.located', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='device',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tag', to='sensors.tag', verbose_name='Marca'),
        ),
    ]
