# Generated by Django 5.0.6 on 2024-07-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='located',
            old_name='place',
            new_name='name',
        ),
    ]
