# Generated by Django 5.0.6 on 2024-07-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
