# Generated by Django 5.0.6 on 2024-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='located',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
