# Generated by Django 5.0.6 on 2024-07-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_alter_measures_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measures',
            old_name='fp',
            new_name='FP',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='hz',
            new_name='Hz',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='i1',
            new_name='Ia',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='i2',
            new_name='Ib',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='i3',
            new_name='Ic',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='p1',
            new_name='Pa',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='p2',
            new_name='Pb',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='p3',
            new_name='Pc',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='v1',
            new_name='Va',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='v12',
            new_name='Vab',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='v2',
            new_name='Vb',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='v23',
            new_name='Vbc',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='v3',
            new_name='Vc',
        ),
        migrations.RenameField(
            model_name='measures',
            old_name='v13',
            new_name='Vca',
        ),
    ]
